# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseReadingPreferences(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ReadingPreferences']] = 'ReadingPreferences'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ReadingPreferencesActions[_PrismaModelT]':
        from .client import get_client

        return actions.ReadingPreferencesActions[_PrismaModelT](client or get_client(), cls)


class BaseLearningProgress(_PrismaModel):
    __prisma_model__: ClassVar[Literal['LearningProgress']] = 'LearningProgress'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.LearningProgressActions[_PrismaModelT]':
        from .client import get_client

        return actions.LearningProgressActions[_PrismaModelT](client or get_client(), cls)


class BaseGameScore(_PrismaModel):
    __prisma_model__: ClassVar[Literal['GameScore']] = 'GameScore'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.GameScoreActions[_PrismaModelT]':
        from .client import get_client

        return actions.GameScoreActions[_PrismaModelT](client or get_client(), cls)


class BaseActivity(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Activity']] = 'Activity'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ActivityActions[_PrismaModelT]':
        from .client import get_client

        return actions.ActivityActions[_PrismaModelT](client or get_client(), cls)


class BaseReadingSession(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ReadingSession']] = 'ReadingSession'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ReadingSessionActions[_PrismaModelT]':
        from .client import get_client

        return actions.ReadingSessionActions[_PrismaModelT](client or get_client(), cls)


class BaseReadingEvent(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ReadingEvent']] = 'ReadingEvent'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ReadingEventActions[_PrismaModelT]':
        from .client import get_client

        return actions.ReadingEventActions[_PrismaModelT](client or get_client(), cls)


class BaseSpellingError(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SpellingError']] = 'SpellingError'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SpellingErrorActions[_PrismaModelT]':
        from .client import get_client

        return actions.SpellingErrorActions[_PrismaModelT](client or get_client(), cls)


class BaseUserProfile(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserProfile']] = 'UserProfile'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserProfileActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserProfileActions[_PrismaModelT](client or get_client(), cls)


class BaseWordDifficulty(_PrismaModel):
    __prisma_model__: ClassVar[Literal['WordDifficulty']] = 'WordDifficulty'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.WordDifficultyActions[_PrismaModelT]':
        from .client import get_client

        return actions.WordDifficultyActions[_PrismaModelT](client or get_client(), cls)


class BaseUserWordHistory(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserWordHistory']] = 'UserWordHistory'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserWordHistoryActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserWordHistoryActions[_PrismaModelT](client or get_client(), cls)


class BaseConceptDiagram(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ConceptDiagram']] = 'ConceptDiagram'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ConceptDiagramActions[_PrismaModelT]':
        from .client import get_client

        return actions.ConceptDiagramActions[_PrismaModelT](client or get_client(), cls)


class BaseDailyProgress(_PrismaModel):
    __prisma_model__: ClassVar[Literal['DailyProgress']] = 'DailyProgress'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.DailyProgressActions[_PrismaModelT]':
        from .client import get_client

        return actions.DailyProgressActions[_PrismaModelT](client or get_client(), cls)


class BaseSkillMastery(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SkillMastery']] = 'SkillMastery'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SkillMasteryActions[_PrismaModelT]':
        from .client import get_client

        return actions.SkillMasteryActions[_PrismaModelT](client or get_client(), cls)


class BaseReadingCoachSession(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ReadingCoachSession']] = 'ReadingCoachSession'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ReadingCoachSessionActions[_PrismaModelT]':
        from .client import get_client

        return actions.ReadingCoachSessionActions[_PrismaModelT](client or get_client(), cls)


