# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('/Users/apple/Downloads/NeuroVidya MIni Project/backend/prisma/schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'darwin-arm64': '/Users/apple/Downloads/NeuroVidya MIni Project/backend/node_modules/prisma/query-engine-darwin-arm64'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    user: 'actions.UserActions[models.User]'
    readingpreferences: 'actions.ReadingPreferencesActions[models.ReadingPreferences]'
    learningprogress: 'actions.LearningProgressActions[models.LearningProgress]'
    gamescore: 'actions.GameScoreActions[models.GameScore]'
    activity: 'actions.ActivityActions[models.Activity]'
    readingsession: 'actions.ReadingSessionActions[models.ReadingSession]'
    readingevent: 'actions.ReadingEventActions[models.ReadingEvent]'
    spellingerror: 'actions.SpellingErrorActions[models.SpellingError]'
    userprofile: 'actions.UserProfileActions[models.UserProfile]'
    worddifficulty: 'actions.WordDifficultyActions[models.WordDifficulty]'
    userwordhistory: 'actions.UserWordHistoryActions[models.UserWordHistory]'
    conceptdiagram: 'actions.ConceptDiagramActions[models.ConceptDiagram]'
    dailyprogress: 'actions.DailyProgressActions[models.DailyProgress]'
    skillmastery: 'actions.SkillMasteryActions[models.SkillMastery]'
    readingcoachsession: 'actions.ReadingCoachSessionActions[models.ReadingCoachSession]'

    __slots__ = (
        'user',
        'readingpreferences',
        'learningprogress',
        'gamescore',
        'activity',
        'readingsession',
        'readingevent',
        'spellingerror',
        'userprofile',
        'worddifficulty',
        'userwordhistory',
        'conceptdiagram',
        'dailyprogress',
        'skillmastery',
        'readingcoachsession',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set([]),
            active_provider='sqlite',
            default_datasource_name='db',
        )

        self.user = actions.UserActions[models.User](self, models.User)
        self.readingpreferences = actions.ReadingPreferencesActions[models.ReadingPreferences](self, models.ReadingPreferences)
        self.learningprogress = actions.LearningProgressActions[models.LearningProgress](self, models.LearningProgress)
        self.gamescore = actions.GameScoreActions[models.GameScore](self, models.GameScore)
        self.activity = actions.ActivityActions[models.Activity](self, models.Activity)
        self.readingsession = actions.ReadingSessionActions[models.ReadingSession](self, models.ReadingSession)
        self.readingevent = actions.ReadingEventActions[models.ReadingEvent](self, models.ReadingEvent)
        self.spellingerror = actions.SpellingErrorActions[models.SpellingError](self, models.SpellingError)
        self.userprofile = actions.UserProfileActions[models.UserProfile](self, models.UserProfile)
        self.worddifficulty = actions.WordDifficultyActions[models.WordDifficulty](self, models.WordDifficulty)
        self.userwordhistory = actions.UserWordHistoryActions[models.UserWordHistory](self, models.UserWordHistory)
        self.conceptdiagram = actions.ConceptDiagramActions[models.ConceptDiagram](self, models.ConceptDiagram)
        self.dailyprogress = actions.DailyProgressActions[models.DailyProgress](self, models.DailyProgress)
        self.skillmastery = actions.SkillMasteryActions[models.SkillMastery](self, models.SkillMastery)
        self.readingcoachsession = actions.ReadingCoachSessionActions[models.ReadingCoachSession](self, models.ReadingCoachSession)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'DATABASE_URL'}).resolve(),
            'source_file_path': '/Users/apple/Downloads/NeuroVidya MIni Project/backend/prisma/schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    user: 'UserBatchActions'
    readingpreferences: 'ReadingPreferencesBatchActions'
    learningprogress: 'LearningProgressBatchActions'
    gamescore: 'GameScoreBatchActions'
    activity: 'ActivityBatchActions'
    readingsession: 'ReadingSessionBatchActions'
    readingevent: 'ReadingEventBatchActions'
    spellingerror: 'SpellingErrorBatchActions'
    userprofile: 'UserProfileBatchActions'
    worddifficulty: 'WordDifficultyBatchActions'
    userwordhistory: 'UserWordHistoryBatchActions'
    conceptdiagram: 'ConceptDiagramBatchActions'
    dailyprogress: 'DailyProgressBatchActions'
    skillmastery: 'SkillMasteryBatchActions'
    readingcoachsession: 'ReadingCoachSessionBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.user = UserBatchActions(self)
        self.readingpreferences = ReadingPreferencesBatchActions(self)
        self.learningprogress = LearningProgressBatchActions(self)
        self.gamescore = GameScoreBatchActions(self)
        self.activity = ActivityBatchActions(self)
        self.readingsession = ReadingSessionBatchActions(self)
        self.readingevent = ReadingEventBatchActions(self)
        self.spellingerror = SpellingErrorBatchActions(self)
        self.userprofile = UserProfileBatchActions(self)
        self.worddifficulty = WordDifficultyBatchActions(self)
        self.userwordhistory = UserWordHistoryBatchActions(self)
        self.conceptdiagram = ConceptDiagramBatchActions(self)
        self.dailyprogress = DailyProgressBatchActions(self)
        self.skillmastery = SkillMasteryBatchActions(self)
        self.readingcoachsession = ReadingCoachSessionBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserCreateInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.User,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.User,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserUpdateInput,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.User,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserWhereUniqueInput,
        data: types.UserUpsertInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserUpdateManyMutationInput,
        where: types.UserWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.User,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.User,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ReadingPreferencesBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ReadingPreferencesCreateInput,
        include: Optional[types.ReadingPreferencesInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ReadingPreferences,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ReadingPreferencesCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ReadingPreferences,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ReadingPreferencesWhereUniqueInput,
        include: Optional[types.ReadingPreferencesInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ReadingPreferences,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ReadingPreferencesUpdateInput,
        where: types.ReadingPreferencesWhereUniqueInput,
        include: Optional[types.ReadingPreferencesInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ReadingPreferences,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ReadingPreferencesWhereUniqueInput,
        data: types.ReadingPreferencesUpsertInput,
        include: Optional[types.ReadingPreferencesInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ReadingPreferences,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ReadingPreferencesUpdateManyMutationInput,
        where: types.ReadingPreferencesWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ReadingPreferences,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ReadingPreferencesWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ReadingPreferences,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class LearningProgressBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.LearningProgressCreateInput,
        include: Optional[types.LearningProgressInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.LearningProgress,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.LearningProgressCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.LearningProgress,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.LearningProgressWhereUniqueInput,
        include: Optional[types.LearningProgressInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.LearningProgress,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.LearningProgressUpdateInput,
        where: types.LearningProgressWhereUniqueInput,
        include: Optional[types.LearningProgressInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.LearningProgress,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.LearningProgressWhereUniqueInput,
        data: types.LearningProgressUpsertInput,
        include: Optional[types.LearningProgressInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.LearningProgress,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.LearningProgressUpdateManyMutationInput,
        where: types.LearningProgressWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.LearningProgress,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.LearningProgressWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.LearningProgress,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class GameScoreBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.GameScoreCreateInput,
        include: Optional[types.GameScoreInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.GameScore,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.GameScoreCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.GameScore,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.GameScoreWhereUniqueInput,
        include: Optional[types.GameScoreInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.GameScore,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.GameScoreUpdateInput,
        where: types.GameScoreWhereUniqueInput,
        include: Optional[types.GameScoreInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.GameScore,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.GameScoreWhereUniqueInput,
        data: types.GameScoreUpsertInput,
        include: Optional[types.GameScoreInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.GameScore,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.GameScoreUpdateManyMutationInput,
        where: types.GameScoreWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.GameScore,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.GameScoreWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.GameScore,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ActivityBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ActivityCreateInput,
        include: Optional[types.ActivityInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Activity,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ActivityCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Activity,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ActivityWhereUniqueInput,
        include: Optional[types.ActivityInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Activity,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ActivityUpdateInput,
        where: types.ActivityWhereUniqueInput,
        include: Optional[types.ActivityInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Activity,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ActivityWhereUniqueInput,
        data: types.ActivityUpsertInput,
        include: Optional[types.ActivityInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Activity,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ActivityUpdateManyMutationInput,
        where: types.ActivityWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Activity,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ActivityWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Activity,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ReadingSessionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ReadingSessionCreateInput,
        include: Optional[types.ReadingSessionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ReadingSession,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ReadingSessionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ReadingSession,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ReadingSessionWhereUniqueInput,
        include: Optional[types.ReadingSessionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ReadingSession,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ReadingSessionUpdateInput,
        where: types.ReadingSessionWhereUniqueInput,
        include: Optional[types.ReadingSessionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ReadingSession,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ReadingSessionWhereUniqueInput,
        data: types.ReadingSessionUpsertInput,
        include: Optional[types.ReadingSessionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ReadingSession,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ReadingSessionUpdateManyMutationInput,
        where: types.ReadingSessionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ReadingSession,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ReadingSessionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ReadingSession,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ReadingEventBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ReadingEventCreateInput,
        include: Optional[types.ReadingEventInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ReadingEvent,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ReadingEventCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ReadingEvent,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ReadingEventWhereUniqueInput,
        include: Optional[types.ReadingEventInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ReadingEvent,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ReadingEventUpdateInput,
        where: types.ReadingEventWhereUniqueInput,
        include: Optional[types.ReadingEventInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ReadingEvent,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ReadingEventWhereUniqueInput,
        data: types.ReadingEventUpsertInput,
        include: Optional[types.ReadingEventInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ReadingEvent,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ReadingEventUpdateManyMutationInput,
        where: types.ReadingEventWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ReadingEvent,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ReadingEventWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ReadingEvent,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class SpellingErrorBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.SpellingErrorCreateInput,
        include: Optional[types.SpellingErrorInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.SpellingError,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.SpellingErrorCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.SpellingError,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.SpellingErrorWhereUniqueInput,
        include: Optional[types.SpellingErrorInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.SpellingError,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.SpellingErrorUpdateInput,
        where: types.SpellingErrorWhereUniqueInput,
        include: Optional[types.SpellingErrorInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.SpellingError,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.SpellingErrorWhereUniqueInput,
        data: types.SpellingErrorUpsertInput,
        include: Optional[types.SpellingErrorInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.SpellingError,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.SpellingErrorUpdateManyMutationInput,
        where: types.SpellingErrorWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.SpellingError,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.SpellingErrorWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.SpellingError,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserProfileBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserProfileCreateInput,
        include: Optional[types.UserProfileInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserProfile,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserProfileCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserProfile,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserProfileWhereUniqueInput,
        include: Optional[types.UserProfileInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserProfile,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserProfileUpdateInput,
        where: types.UserProfileWhereUniqueInput,
        include: Optional[types.UserProfileInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserProfile,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserProfileWhereUniqueInput,
        data: types.UserProfileUpsertInput,
        include: Optional[types.UserProfileInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserProfile,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserProfileUpdateManyMutationInput,
        where: types.UserProfileWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserProfile,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserProfileWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserProfile,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class WordDifficultyBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.WordDifficultyCreateInput,
        include: Optional[types.WordDifficultyInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.WordDifficulty,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.WordDifficultyCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.WordDifficulty,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.WordDifficultyWhereUniqueInput,
        include: Optional[types.WordDifficultyInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.WordDifficulty,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.WordDifficultyUpdateInput,
        where: types.WordDifficultyWhereUniqueInput,
        include: Optional[types.WordDifficultyInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.WordDifficulty,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.WordDifficultyWhereUniqueInput,
        data: types.WordDifficultyUpsertInput,
        include: Optional[types.WordDifficultyInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.WordDifficulty,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.WordDifficultyUpdateManyMutationInput,
        where: types.WordDifficultyWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.WordDifficulty,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.WordDifficultyWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.WordDifficulty,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserWordHistoryBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserWordHistoryCreateInput,
        include: Optional[types.UserWordHistoryInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserWordHistory,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserWordHistoryCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserWordHistory,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserWordHistoryWhereUniqueInput,
        include: Optional[types.UserWordHistoryInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserWordHistory,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserWordHistoryUpdateInput,
        where: types.UserWordHistoryWhereUniqueInput,
        include: Optional[types.UserWordHistoryInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserWordHistory,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserWordHistoryWhereUniqueInput,
        data: types.UserWordHistoryUpsertInput,
        include: Optional[types.UserWordHistoryInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserWordHistory,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserWordHistoryUpdateManyMutationInput,
        where: types.UserWordHistoryWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserWordHistory,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserWordHistoryWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserWordHistory,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ConceptDiagramBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ConceptDiagramCreateInput,
        include: Optional[types.ConceptDiagramInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ConceptDiagram,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ConceptDiagramCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ConceptDiagram,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ConceptDiagramWhereUniqueInput,
        include: Optional[types.ConceptDiagramInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ConceptDiagram,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ConceptDiagramUpdateInput,
        where: types.ConceptDiagramWhereUniqueInput,
        include: Optional[types.ConceptDiagramInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ConceptDiagram,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ConceptDiagramWhereUniqueInput,
        data: types.ConceptDiagramUpsertInput,
        include: Optional[types.ConceptDiagramInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ConceptDiagram,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ConceptDiagramUpdateManyMutationInput,
        where: types.ConceptDiagramWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ConceptDiagram,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ConceptDiagramWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ConceptDiagram,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class DailyProgressBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.DailyProgressCreateInput,
        include: Optional[types.DailyProgressInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.DailyProgress,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.DailyProgressCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.DailyProgress,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.DailyProgressWhereUniqueInput,
        include: Optional[types.DailyProgressInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.DailyProgress,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.DailyProgressUpdateInput,
        where: types.DailyProgressWhereUniqueInput,
        include: Optional[types.DailyProgressInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.DailyProgress,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.DailyProgressWhereUniqueInput,
        data: types.DailyProgressUpsertInput,
        include: Optional[types.DailyProgressInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.DailyProgress,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.DailyProgressUpdateManyMutationInput,
        where: types.DailyProgressWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.DailyProgress,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.DailyProgressWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.DailyProgress,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class SkillMasteryBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.SkillMasteryCreateInput,
        include: Optional[types.SkillMasteryInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.SkillMastery,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.SkillMasteryCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.SkillMastery,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.SkillMasteryWhereUniqueInput,
        include: Optional[types.SkillMasteryInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.SkillMastery,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.SkillMasteryUpdateInput,
        where: types.SkillMasteryWhereUniqueInput,
        include: Optional[types.SkillMasteryInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.SkillMastery,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.SkillMasteryWhereUniqueInput,
        data: types.SkillMasteryUpsertInput,
        include: Optional[types.SkillMasteryInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.SkillMastery,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.SkillMasteryUpdateManyMutationInput,
        where: types.SkillMasteryWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.SkillMastery,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.SkillMasteryWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.SkillMastery,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ReadingCoachSessionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ReadingCoachSessionCreateInput,
        include: Optional[types.ReadingCoachSessionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ReadingCoachSession,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ReadingCoachSessionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ReadingCoachSession,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ReadingCoachSessionWhereUniqueInput,
        include: Optional[types.ReadingCoachSessionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ReadingCoachSession,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ReadingCoachSessionUpdateInput,
        where: types.ReadingCoachSessionWhereUniqueInput,
        include: Optional[types.ReadingCoachSessionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ReadingCoachSession,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ReadingCoachSessionWhereUniqueInput,
        data: types.ReadingCoachSessionUpsertInput,
        include: Optional[types.ReadingCoachSessionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ReadingCoachSession,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ReadingCoachSessionUpdateManyMutationInput,
        where: types.ReadingCoachSessionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ReadingCoachSession,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ReadingCoachSessionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ReadingCoachSession,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma