from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'ReadingPreferences',
    'LearningProgress',
    'GameScore',
    'Activity',
    'ReadingSession',
    'ReadingEvent',
    'SpellingError',
    'UserProfile',
    'WordDifficulty',
    'UserWordHistory',
    'ConceptDiagram',
    'DailyProgress',
    'SkillMastery',
    'ReadingCoachSession',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'preferences': 'ReadingPreferences',
        'progress': 'LearningProgress',
        'gameScores': 'GameScore',
        'activities': 'Activity',
        'readingSessions': 'ReadingSession',
        'spellingErrors': 'SpellingError',
        'userProfile': 'UserProfile',
        'userWordHistory': 'UserWordHistory',
        'dailyProgress': 'DailyProgress',
        'skillMastery': 'SkillMastery',
        'conceptDiagrams': 'ConceptDiagram',
        'readingCoachSessions': 'ReadingCoachSession',
    },
    'ReadingPreferences': {
        'user': 'User',
    },
    'LearningProgress': {
        'user': 'User',
        'readingCoachSessions': 'ReadingCoachSession',
    },
    'GameScore': {
        'user': 'User',
    },
    'Activity': {
        'user': 'User',
    },
    'ReadingSession': {
        'user': 'User',
        'readingEvents': 'ReadingEvent',
    },
    'ReadingEvent': {
        'session': 'ReadingSession',
    },
    'SpellingError': {
        'user': 'User',
    },
    'UserProfile': {
        'user': 'User',
    },
    'WordDifficulty': {
        'userHistory': 'UserWordHistory',
    },
    'UserWordHistory': {
        'word': 'WordDifficulty',
        'user': 'User',
    },
    'ConceptDiagram': {
        'user': 'User',
    },
    'DailyProgress': {
        'user': 'User',
    },
    'SkillMastery': {
        'user': 'User',
    },
    'ReadingCoachSession': {
        'user': 'User',
        'learningProgress': 'LearningProgress',
    },
}

# fmt: on